name: color_gen
description: Package to assist with color generation for your Flutter projects
version: 0.0.1
repository: https://github.com/SilentCatD/color_gen

environment:
  sdk: '>=2.19.6 <4.0.0'

dependencies:
  path: ^1.8.2
  yaml: ^3.1.2
  dart_style: ^2.3.1

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
